'use client'
//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
    className={localStorage.getItem("darkMode") === "true" ? "dark" : "light"}
    >
      <body className={`${inter.className} dark:bg-slate-900 dark:text-neutral-200`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
